import type { CityNpcDef } from "@/features/types";

export const CITY_NPCS: CityNpcDef[] = [
  { kind: "npc", id: "lin-ran", name: "Lin Ran", nameCn: "林然", role: "现实拆解型职场妈妈", desc: "在工作、育儿与自我成长之间寻找可持续平衡。", dialogue: ["家庭不能依靠某一个人的长期牺牲运行。", "我会同时检查事实、感受、责任分配和可持续性。"], route: "/creator/lin-ran", actionLabel: "查看个人主页", debateAgentId: "lin-ran", color: 0xd48258, spriteFrame: 1, behavior: "patrol", points: [{ x: 190, y: 330 }, { x: 390, y: 340 }, { x: 300, y: 395 }] },
  { kind: "npc", id: "meng-yuxuan", name: "Meng Yuxuan", nameCn: "孟宇轩", role: "航空电子量化工程派", desc: "深耕航空电子、嵌入式与多模态 AI 落地。", dialogue: ["方案先量化、再分模块，最后进入真实工作流。", "安全、隐私、法律与学术诚信不可交换。"], route: "/creator/meng-yuxuan", actionLabel: "查看个人主页", debateAgentId: "meng-yuxuan", color: 0x4f7995, spriteFrame: 2, behavior: "patrol", points: [{ x: 480, y: 350 }, { x: 720, y: 332 }, { x: 620, y: 405 }] },
  { kind: "npc", id: "li-minghan", name: "Li Minghan", nameCn: "李明翰", role: "底层原理与证据链研究派", desc: "连接工程落地、计算机视觉和多模态 Agent。", dialogue: ["结论必须能追溯到定义、原始证据或可复现实验。", "先理解底层原理，再搭建完整技术链路。"], route: "/creator/li-minghan", actionLabel: "查看个人主页", debateAgentId: "li-minghan", color: 0x7b6c9c, spriteFrame: 3, behavior: "patrol", points: [{ x: 820, y: 330 }, { x: 980, y: 360 }, { x: 900, y: 400 }] },
  { kind: "npc", id: "product-editor", name: "Yan Qing", nameCn: "砚青", role: "产品主编", desc: "从用户、命题与取舍出发，把创意压缩成可交付的核心。", dialogue: ["先把命题压成一句话。", "删掉它会影响核心价值吗？"], route: "/chat-debate/?profile=product-editor", actionLabel: "进入创作议事厅", debateAgentId: "product-editor", color: 0xd39930, spriteFrame: 4, behavior: "patrol", points: [{ x: 180, y: 645 }, { x: 420, y: 650 }, { x: 320, y: 625 }] },
  { kind: "npc", id: "growth-strategist", name: "Jian Wei", nameCn: "见微", role: "增长策略师", desc: "用可测假设检查触达、激活、留存与传播闭环。", dialogue: ["先定义一次有效使用。", "这个增长最终能留住谁？"], route: "/chat-debate/?profile=growth-strategist", actionLabel: "进入创作议事厅", debateAgentId: "growth-strategist", color: 0x5b9b66, spriteFrame: 5, behavior: "patrol", points: [{ x: 470, y: 650 }, { x: 740, y: 650 }, { x: 600, y: 615 }] },
  { kind: "npc", id: "systems-builder", name: "Bei Chen", nameCn: "北辰", role: "系统工程师", desc: "把作品拆成数据流、状态机、失败边界与验收链路。", dialogue: ["状态从哪里来，到哪里去？", "失败路径也要设计。"], route: "/chat-debate/?profile=systems-builder", actionLabel: "进入创作议事厅", debateAgentId: "systems-builder", color: 0x6f8794, spriteFrame: 6, behavior: "patrol", points: [{ x: 760, y: 650 }, { x: 980, y: 642 }, { x: 880, y: 615 }] },
  { kind: "npc", id: "experience-designer", name: "You Lan", nameCn: "游岚", role: "体验设计师", desc: "检查用户旅程、信息层级、状态反馈与无障碍体验。", dialogue: ["用户下一眼会看哪里？", "这个按钮按下去发生什么？"], route: "/chat-debate/?profile=experience-designer", actionLabel: "进入创作议事厅", debateAgentId: "experience-designer", color: 0x8b7ccf, spriteFrame: 7, behavior: "patrol", points: [{ x: 90, y: 390 }, { x: 190, y: 405 }, { x: 140, y: 620 }] },
  { kind: "npc", id: "evidence-researcher", name: "Zhi Heng", nameCn: "知衡", role: "证据研究员", desc: "区分事实、推断和建议，追问来源、时效与反例。", dialogue: ["这条是事实还是推断？", "证据能支持到哪一步？"], route: "/chat-debate/?profile=evidence-researcher", actionLabel: "进入创作议事厅", debateAgentId: "evidence-researcher", color: 0x3fac83, spriteFrame: 8, behavior: "tea", points: [{ x: 350, y: 465 }, { x: 620, y: 465 }, { x: 890, y: 465 }, { x: 650, y: 385 }] },
  { kind: "npc", id: "demo-director", name: "Zhao Ye", nameCn: "照野", role: "演示导演", desc: "用冲突、动作、证据与结果编排一条有说服力的演示路径。", dialogue: ["别描述功能，演给我看。", "三十秒内先让我看见变化。"], route: "/chat-debate/?profile=demo-director", actionLabel: "进入创作议事厅", debateAgentId: "demo-director", color: 0x4d8db7, spriteFrame: 9, behavior: "conversation-a", points: [{ x: 335, y: 355 }, { x: 585, y: 355 }] },
  { kind: "npc", id: "ethics-steward", name: "Shou Zhuo", nameCn: "守拙", role: "伦理守门人", desc: "把隐私、授权、透明度与潜在伤害写进产品边界。", dialogue: ["谁会承担这个风险？", "用户能否拒绝和撤回？"], route: "/chat-debate/?profile=ethics-steward", actionLabel: "进入创作议事厅", debateAgentId: "ethics-steward", color: 0xe7aa45, spriteFrame: 10, behavior: "conversation-b", points: [{ x: 940, y: 355 }, { x: 695, y: 355 }] },
];

export const PATROL_NPCS = CITY_NPCS.filter((npc) => npc.behavior === "patrol");
export const TEA_STEWARD = CITY_NPCS.find((npc) => npc.behavior === "tea")!;
export const CONVERSATION_NPCS = CITY_NPCS.filter((npc) => npc.behavior.startsWith("conversation"));
